version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: pmu-timescaledb
    environment:
      - POSTGRES_DB=pmu_concentrator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123  # Set a password
      - POSTGRES_HOST_AUTH_METHOD=password
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: pmu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescale-data:
  redis-data: